// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1594473048);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1594473168);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1594535830);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1594528510);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1594472928);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1594045565);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1594473288);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 465659);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.lastDir", "/root/Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1594044455);
user_pref("browser.laterrun.bookkeeping.sessionCount", 17);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2e5a9e5f-8663-4caa-a6d5-5d7e5ae98956}");
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\",\"wappalyzer_crunchlabz_com\"],\"idsInUrlbar\":[\"pocket\",\"wappalyzer_crunchlabz_com\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1594535715677");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1594537509677");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1594535699145");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1594539299145");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200622191537");
user_pref("browser.slowStartup.averageTime", 4415);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200622191537");
user_pref("browser.startup.homepage_override.mstone", "68.10.0");
user_pref("browser.startup.lastColdStartupCheck", 1594524883);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.10.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Mon, 06 Jul 2020 20:23:11 GMT");
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1594473049);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200622191537");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.wappalyzer@crunchlabz.com", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"eabc2e7c-ffde-4803-ac98-075e7b5d3510\",\"fxmonitor@mozilla.org\":\"63240162-c75b-4300-933b-e49740c3c5ba\",\"screenshots@mozilla.org\":\"69b9086a-0e94-4ea4-a3b5-aca96406925a\",\"webcompat-reporter@mozilla.org\":\"dadbadde-d03d-4023-b4de-90af15226864\",\"webcompat@mozilla.org\":\"05854a1c-606d-420f-8ac0-e828bb190a73\",\"default-theme@mozilla.org\":\"51579a48-26f7-46e0-9c53-c5e8774a9bec\",\"google@search.mozilla.org\":\"d0f078f5-af81-4366-9f4c-45abce5c5e87\",\"amazondotcom@search.mozilla.org\":\"7b74ff4a-1e37-4499-b78e-d523420bb3d9\",\"bing@search.mozilla.org\":\"ca6707fe-cef2-47bc-8a64-2b0616387a8a\",\"ddg@search.mozilla.org\":\"8ff63f00-93bf-4b73-a594-c190398011b8\",\"ebay@search.mozilla.org\":\"87098896-07ab-48ac-a00e-f0fb15e62481\",\"twitter@search.mozilla.org\":\"634b5240-85fc-4d90-8d87-6bcc81432a5c\",\"wikipedia@search.mozilla.org\":\"3a5b57db-bb11-47a7-a40f-29f3f8c23cb8\",\"wappalyzer@crunchlabz.com\":\"6ba1a386-71d0-4a46-a86a-19922f8d16a3\"}");
user_pref("font.internaluseonly.changed", false);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1594474412);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1594131661);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200622191537");
user_pref("media.gmp-manager.lastCheck", 1594473890);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1594046274);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "f7a5d253-93df-4729-86ab-1de7b4d046c5");
user_pref("security.sandbox.plugin.tempDirSuffix", "d0a2eb51-cc1a-48ca-8e60-4d6d9103f585");
user_pref("services.blocklist.pinning.checked", 1594472931);
user_pref("services.settings.clock_skew_seconds", -4);
user_pref("services.settings.last_etag", "\"1594426281034\"");
user_pref("services.settings.last_update_seconds", 1594472931);
user_pref("services.settings.main.cfr-fxa.last_check", 1594472931);
user_pref("services.settings.main.cfr.last_check", 1594472931);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1594472931);
user_pref("services.settings.main.hijack-blocklists.last_check", 1594472931);
user_pref("services.settings.main.language-dictionaries.last_check", 1594472931);
user_pref("services.settings.main.sites-classification.last_check", 1594472931);
user_pref("services.settings.main.tippytop.last_check", 1594472931);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1594472931);
user_pref("services.settings.security.onecrl.checked", 1594472931);
user_pref("signon.autofillForms", false);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1594046274);
user_pref("toolkit.startup.last_success", 1594524876);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200622191537");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
